### PR TITLE
Added a way to adjust resolvconf options

### LINKED ISSUE #14: Add a way to adjust resolvconf options
##### ISSUE TYPE

 - Feature Idea

##### ROLE VERSION

```
2.0.0
```

##### SUMMARY

In order to adjust the options of resolvconf, like `rotate`, `timeout`, etc., it would be appreciated to have a config option for this.

##### STEPS TO REPRODUCE

```yaml

```

```
```

### PR DESCRIPTION
**Pull request by olafnorge**
Added `resolver_options` variable in order to set options like `timeout`, `rotate`, etc. to the resolv.conf. Fixes: https://github.com/reallyenglish/ansible-role-resolver/issues/14

### CODE REVIEW

**Review by trombik — CHANGES_REQUESTED** [review]
thanks for the pr. Would you add examples in the spec file? Simple file resource test with match expectations would be sufficient.

**Comment by olafnorge** [comment]
@trombik How can I check the results of the Jenkins build? For me the domain of the Jenkins does not resolve.

**Comment by trombik** [comment]
see my comments in #18

**Comment by trombik** [comment]
superseded by #18

**Pull request closed without merging**
